name: Sync Tracks to Supabase

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Кожні 30 хвилин

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run supabase sync
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          HISTORY_JSON_URL: ${{ secrets.HISTORY_JSON_URL }}
        run: python supabase_sync.py
