name: Update Tracks

on:
  schedule:
    - cron: "0 * * * *" # кожну годину
  workflow_dispatch: # запуск вручну

jobs:
  update-tracks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Update tracks
        run: node parser_radioco_history.js

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push changes
        run: |
          git add tracks.json
          git commit -m "Update tracks [bot]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
